name: maana_main_project_2
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  provider: ^4.3.2+2
  shared_preferences: ^0.5.12+2
  flutter_icons: ^1.1.0
  fluttertoast: ^7.1.1
  cached_network_image: any
  uuid: ^2.2.2
  ff_navigation_bar: ^0.1.5
  path_provider: ^1.6.22
  permission_handler:
  shimmer: ^1.1.2
  flutter_svg: any
  flutter_spinkit: ^4.1.2+1
  dio: ^3.0.10
  advance_pdf_viewer: any
  lottie: ^0.7.0+1
  rounded_loading_button: any
  email_validator: '^1.0.5'
  webview_flutter: ^1.0.7
  share: ^0.6.5+4
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/images/
    - assets/icons/
    - assets/launcher/icon.jpg
    - assets/books.json
    - assets/user.json
    
  uses-material-design: true



